### ISSUE TITLE
homebridge instantly crashes

### ISSUE THREAD

**Issue by Starbix** [Danimal4326/homebridge-hyperion#11]
I already downgraded color to 0.10.0 with `sudo npm install  --unsafe-perm -g color@0.10.0`
but still:
```*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[12/23/2016, 11:26:14 PM] Loaded plugin: homebridge-hyperion
[12/23/2016, 11:26:14 PM] Registering accessory 'homebridge-hyperion.Hyperion'
[12/23/2016, 11:26:14 PM] ---
[12/23/2016, 11:26:14 PM] Loaded config.json with 2 accessories and 0 platforms.
[12/23/2016, 11:26:14 PM] ---
[12/23/2016, 11:26:14 PM] Loading 0 platforms...
[12/23/2016, 11:26:14 PM] Loading 2 accessories...
[12/23/2016, 11:26:14 PM] [Ambilight] Initializing Hyperion accessory...
[12/23/2016, 11:26:14 PM] [Ambilight] Starting Hyperion Accessory
[12/23/2016, 11:26:14 PM] [Regal] Initializing Hyperion accessory...
[12/23/2016, 11:26:14 PM] [Regal] Starting Hyperion Accessory
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[12/23/2016, 11:26:14 PM] Homebridge is running on port 51826.
[12/23/2016, 11:26:15 PM] [Regal] Setting power state on the 'Regal' to on
/usr/lib/node_modules/homebridge-hyperion/index.js:41
                color: color.rgbArray()
                             ^

TypeError: color.rgbArray is not a function
    at HyperionAccessory.sendHyperionCommand (/usr/lib/node_modules/homebridge-hyperion/index.js:41:30)
    at HyperionAccessory.setPowerState (/usr/lib/node_modules/homebridge-hyperion/index.js:92:10)
    at emitMany (events.js:127:13)
    at emit (events.js:201:7)
    at Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:740:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:685:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:201:7)
```

**Comment by icurnvs** [comment]
Same here!

**Comment by fugazzy** [comment]
Goto /usr/lib/node_modules/homebridge-hyperion/
delete color
npm install color@0.10.0
(yes, without -g !!)
maybe also delete color directly in /usr/lib/node_modules

**Comment by Starbix** [comment]
Thanks! works again
